Update action.yml static code analysis

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -26,20 +26,20 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3
         
-      # Runs a single command using the runners shell for archive permission gradlew execute
-      - name: Make gradlew executable
-        run: chmod +x ./gradlew
-
-      # Runs a single command using the runners shell for lint execute
-      - name: Run Lint
-        run: ./gradlew lint
-
-      # Runs a set of commands using the runners shell for archive html generate
-      - name: Upload html lint report
-        uses: actions/upload-artifact@v3
-        with: 
-          name: lint.html
-          path: app/build/reports/lint-results-debug.html
+#      # Runs a single command using the runners shell for archive permission gradlew execute
+#      - name: Make gradlew executable
+#        run: chmod +x ./gradlew
+#
+#      # Runs a single command using the runners shell for lint execute
+#      - name: Run Lint
+#        run: ./gradlew lint
+#
+#      # Runs a set of commands using the runners shell for archive html generate
+#      - name: Upload html lint report
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: lint.html
+#          path: app/build/reports/lint-results-debug.html
           
   # This workflow contains a single job called "unit-test"
   unit-test:
@@ -54,21 +54,21 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3
         
-      # Runs a single command using the runners shell for archive permission gradlew execute
-      - name: Make gradlew executable
-        run: chmod +x ./gradlew
-
-      # Runs a single command using the runners shell for unit test execute
-      - name: Run Unit Test
-        run: ./gradlew test
-
-      # Runs a set of commands using the runners shell for archive html generate
-      - name: Upload html test report
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with: 
-          name: unit_test_report
-          path: app/build/reports/tests/testDebugUnitTest/  
+#      # Runs a single command using the runners shell for archive permission gradlew execute
+#      - name: Make gradlew executable
+#        run: chmod +x ./gradlew
+#
+#      # Runs a single command using the runners shell for unit test execute
+#      - name: Run Unit Test
+#        run: ./gradlew test
+#
+#      # Runs a set of commands using the runners shell for archive html generate
+#      - name: Upload html test report
+#        uses: actions/upload-artifact@v3
+#        if: success() || failure()
+#        with:
+#          name: unit_test_report
+#          path: app/build/reports/tests/testDebugUnitTest/
         
         
       # This workflow contains a single job called "instrumentation-test"
@@ -86,10 +86,51 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3
         
+#      # Runs a single command using the runners shell for archive permission gradlew execute
+#      - name: Make gradlew executable
+#        run: chmod +x ./gradlew
+#
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin' # See 'Supported distributions' for available options
+#          java-version: '11'
+#          cache: 'gradle'
+#
+#      # Runs a single command using the runners shell for instrumentation test execute
+#      - name: Run Instrumentation Test
+#        uses: reactivecircus/android-emulator-runner@v2
+#        with:
+#          api-level: 29
+#          script: ./gradlew connectedCheck --stacktrace
+#
+#      # Runs a set of commands using the runners shell for archive html generate
+#      - name: Upload html test report
+#        uses: actions/upload-artifact@v3
+#        if: success() || failure()
+#        with:
+#          name: instrumentation_test_report
+#          path: app/build/results/report/androidTest/connected/
+
+  # This workflow contains a single job called "static-code-analysis"
+  static-code-analysis:
+    # Triggers the workflow on pipeline unit test event
+    needs: [ instrumentation-test ]
+    # If Job unit-test is success
+    if: ${{ success() }}
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - name: Checkout the code
+        uses: actions/checkout@v3
+
       # Runs a single command using the runners shell for archive permission gradlew execute
       - name: Make gradlew executable
         run: chmod +x ./gradlew
-        
+
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -97,18 +138,9 @@ jobs:
           java-version: '11'
           cache: 'gradle'
 
-      # Runs a single command using the runners shell for instrumentation test execute
-      - name: Run Instrumentation Test
-        uses: reactivecircus/android-emulator-runner@v2
-        with: 
-          api-level: 29
-          script: ./gradlew connectedCheck --stacktrace
-
-      # Runs a set of commands using the runners shell for archive html generate
-      - name: Upload html test report
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with: 
-          name: instrumentation_test_report
-          path: app/build/results/report/androidTest/connected/
+      # Runs a single command using the runners shell for static code analysis
+      - name: SonarCloud Scan
+        run: .gradlew app_sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
